name: docker-compose-action
description: Run docker-compose and enforce cleanup after the job finished
author: Smartly.io
inputs:
  composeFile:
    description: "The path to the docker-compose file to use, realtive to the workspace."
    default: "docker-compose.yml"
    required: false

  serviceName:
    description: "The name of the service to use defined in the compose file.  If not given, will run all services."
    # Empty value will be interpreted as "null"/not-given
    default: ""
    required: false

  composeCommand:
    description: "One of `up` or `run` as the main compose command to execute."
    default: "up"
    required: false

  composeArguments:
    description: "Option flags passed to the compose command."
    default: "--abort-on-container-exit"
    required: false

  runCommand:
    description: "Command to run in the container when composeCommand is 'run'; ignored otherwise."
    default: ""
    required: false

  build:
    description: "Explicitly build the service image before running. Implies pull before build."
    default: "false"
    required: false

  push:
    description: "When to push the built image to the registry. 'on:push' means when the trigger event it a push to the branch. Otherwise true/false.  Only runs if 'build' is true."
    default: "on:push"
    required: false

  build-args:
    description: |
      Build arguments to pass to docker-compose build, as a newline separated list.
      Requires "build" option to be set when used.
      Values may not contain commas, as a naive string split is used to parse them.
      e.g:
        build-args: |
          ARG1=value
          ARG2=other
    required: false

  registry-cache:
    description: Domain name of a proxying cache to dockerhub
    required: false
    default: hub.artifactor.ee

outputs:
  container_id:
    description: "The docker ID of the service container run."

runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/index.js'
